version: '2'
services:
  web:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${DBPASSWORD}
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_USER=odoo
