apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  ports:
  - port: 8069
  selector:
    app: odoo
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo
        tier: frontend
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ['sh', '-c']
        args: ["chmod 777 /var/lib/odoo; chmod 777 /mnt/extra-addons"]
        volumeMounts:
        - name: odoo-web-persistent-storage
          mountPath: /var/lib/odoo
        - name: odoo-addons-persistent-storage
          mountPath: /mnt/extra-addons
      containers:
      - image: gchevalley/odoo:11
        name: odoo
        env:
        - name: HOST
          value: odoo-postgres
        - name: USER
          value: odoo
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo
              key: postgres-password
        ports:
        - containerPort: 8069
          name: odoo
        volumeMounts:
        - name: odoo-web-persistent-storage
          mountPath: /var/lib/odoo
        - name: odoo-addons-persistent-storage
          mountPath: /mnt/extra-addons
      volumes:
      - name: odoo-web-persistent-storage
        persistentVolumeClaim:
          claimName: odoo-web-pv-claim
      - name: odoo-addons-persistent-storage
        persistentVolumeClaim:
          claimName: odoo-addons-pv-claim
