apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-postgres-pv-claim
  labels:
    app: odoo
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
